# Generated by Django 5.1.6 on 2025-05-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrador',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='docente',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='username',
        ),
    ]
