# Generated by Django 5.1.6 on 2025-05-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_alter_administrador_managers_alter_baseuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='fecha_ingreso',
        ),
    ]
