# Generated by Django 5.1.6 on 2025-05-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_materia', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('trayecto', models.CharField(max_length=10)),
            ],
        ),
    ]
