# Generated by Django 5.1.6 on 2025-06-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='carrera',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='trimestre',
            field=models.CharField(default=1, max_length=10, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='trayecto',
            field=models.CharField(max_length=50),
        ),
    ]
