# Generated by Django 5.1.6 on 2025-05-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nombre',
        ),
        migrations.AddField(
            model_name='materia',
            name='codigo_materia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='descripcion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='trayecto',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
