# Generated by Django 5.1.6 on 2025-06-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia_carrera_materia_trimestre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='trimestre',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
