# Generated by Django 5.1.6 on 2025-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='foto_selfie',
            field=models.ImageField(default=1, upload_to='asistencias/selfies/'),
            preserve_default=False,
        ),
    ]
