# Generated by Django 5.1.6 on 2025-06-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_asistencia_foto_selfie'),
        ('materias', '0003_alter_materia_trimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materias.materia'),
        ),
    ]
