# Generated by Django 5.1.6 on 2025-05-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('Agroalimentación', 'Agroalimentación'), ('Construcción Civil', 'Construcción Civil'), ('Electricidad', 'Electricidad'), ('Informática', 'Informática'), ('Ingeniería de Mantenimiento', 'Ingeniería de Mantenimiento'), ('Mecánica', 'Mecánica'), ('Procesamiento y Control de Alimentos', 'Procesamiento y Control de Alimentos')], max_length=50)),
                ('tipo', models.CharField(choices=[('Aula', 'Aula'), ('Laboratorio', 'Laboratorio')], max_length=20)),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
    ]
