# Generated by Django 5.1.6 on 2025-05-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_aula', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('capacidad', models.PositiveIntegerField()),
                ('estatus', models.CharField(max_length=30)),
                ('sede', models.CharField(max_length=50)),
                ('serial', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
